--- 
before_script: 
  - "export TZ='Asia/Shanghai'"
  - "git config user.name \"Charles0429\""
  - "git config user.email \"xiezhenjiang@gmail.com\""
  - "sed -i \"s/github_token/${GH_TOKEN}/g\" _config.yml || exit 1"
branches: 
  only: 
    - master
cache: 
  directories: 
    - node_modules
install: 
  - "npm install hexo-cli -g"
  - "npm install cross-env"
  - "npm install"
language: node_js
node_js: 
  - 14
os: linux
script: 
  - "hexo clean"
  - cross-env YUQUE_TOKEN=$yuque_token npm run deploy
  - "hexo generate"
  - "hexo deploy"
